import Head from "next/head";
import Button from "../components/button";
import Input from "../components/input";
import styles from "../styles/Home.module.css";
import {getAllUsers, User, getUserByName } from "../apis/get-all-users";
import { SetStateAction, useEffect, useState } from "react";
import Card from "../components/card";

// Dummy users data this will need to be fetched from the api
// Implement this in the apis/get-all-users file more instructions there

/**
 * This is the function that is called as soon as this page is routed to which is localhost:3000
 * @returns JSX.Element
 */
export default function Home(): any {
  const [users, setUsers] = useState<User[]>([]);
  const [search, setSearch] = useState("");
  const [visible, setVisible] = useState(false);
  
  useEffect(() => {
    getAllUsers().then((users) => {
      setUsers(users);
    });
    }, []);
    console.log(users);

    function renderUsers() {
      return users.map((user) => {
        
        return( 
          <Card user={user} /> 
        )
      }
      )
    }


    const handleClick = () => {getAllUsers().then((users) => {
      setUsers(users);
      window.location.reload();

      })};


  return (
    <div className={styles.container}>
      <Head>
        <title>Vidzing React Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div className={styles.title}>
        <h1>Vidzing Test</h1>
        <p>By Prajwal Bhagath</p>
        </div>
      <div className={styles.Grid}>
       <div className={styles.cardGrid}>
        {renderUsers()}
        </div>
        <div className={styles.button}>
        <Button onClick={handleClick}>Click Me!</Button>
        </div>
        </div>
        </div>
      </div>
  );
}

